name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'https://paulolata.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev
        
  deploy-pro:
    runs-on: ubuntu-latest
    environment:
      name: producao
      url: 'https://nicolasSoaresHenrique1233456789.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script producao
        run: echo Deploy Produção
